### ISSUE TITLE
Version 1.9.1 - Segmentation Fault Error (Core Dumped) HiveOs

### ISSUE THREAD

**Issue by jvxis** [dero-am/astrobwt-miner#11]
Hi, I'm testing the new version. Either modern or generic is not working and showing this error.

The intels i5 are working well

![Imagem do WhatsApp de 2023-05-12 à(s) 06 42 28](https://github.com/dero-am/astrobwt-miner/assets/108929149/33e61598-62c1-4595-8100-da093982a6fc)

Can you check please?
Thanks,
JVX

**Comment by bernaction** [comment]
Same error here.
Intel CPUs are ok, but Ryzen with segmentation fault

**Comment by dero-am** [comment]
@jvxis @bernaction the fix for hiveOS is uploaded on github with the suffix _R1.
we rolled back some optimization in the code and will release them again in v1.9.2

**Comment by bernaction** [comment]
> @jvxis @bernaction the fix for hiveOS is uploaded on github with the suffix _R1. we rolled back some optimization in the code and will release them again in v1.9.2

thanks, its works now, on Ryzen Zen2 and Zen3, and Intel 10th gen.
