### ISSUE TITLE
Version 1.9.1 -  on Hiveos - Parser Job Error

### ISSUE THREAD

**Issue by jvxis** [dero-am/astrobwt-miner#12]
After a while, All rigs using an Intel CPU went off with a message of Parser Error.
Thanks
JVX

**Comment by dero-am** [comment]
@jvxis please test with `R1` version. feel free to reopen this since this error is not expected.

**Comment by jvxis** [comment]
This is the error. It is still happening. Now Intel and Ryzens with the same problem.
![image](https://github.com/dero-am/astrobwt-miner/assets/108929149/fa5b53c2-cc95-4d08-b53d-571f46ff950b)
