### ISSUE TITLE
Version 1.9.1 R1 Hiveos - Parser Job Error

### ISSUE THREAD

**Issue by jvxis** [dero-am/astrobwt-miner#13]
Happening on Intel and Ryzen Rigs
![image](https://github.com/dero-am/astrobwt-miner/assets/108929149/c1b8907e-a8ce-48c5-a51d-5f4829aacc29)

**Comment by dero-am** [comment]
@jvxis  can you try with community-pools.mysrv.cloud, or any other official node?
On this version, miner sends hashrate update to hansen33 nodes, which I suspect it causes some problems with older hansen33 node.

**Comment by dero-am** [comment]
thanks for reporting this, the root cause is found, please run rev 2 version @jvxis

**Comment by jvxis** [comment]
> @jvxis can you try with community-pools.mysrv.cloud, or any other official node? On this version, miner sends hashrate update to hansen33 nodes, which I suspect it causes some problems with older hansen33 node.

We use the same version as community-pools does

**Comment by jvxis** [comment]
> thanks for reporting this, the root cause is found, please run rev 2 version @jvxis

Testing it now. So far, so good. Thanks.
