### ISSUE TITLE
Problem to start miner under debian and ubuntu

### ISSUE THREAD

**Issue by AlexanderGalchenko** [dero-am/astrobwt-miner#2]
I have a problem to start miner under debian and ubuntu. Miner can't connect to pool, But if i boot in hiveos, all works fine.
I try all version. Work only in hive.

 uname -a
Linux server 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

starts

 ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6x37y4w9xuszcqzfh5yy.Srv1  -r community-pools.mysrv.cloud:10300 -p rpc -m 12

-------------------------------------------
| MINER_VERSION: astrominer 1.8 BETA 2
| COMPILED_TIME: Mar 10 2023
| MINER_AUTHOR: astrominer
| Pool: community-pools.mysrv.cloud:10300
| Pool (failed over 1): null
| Pool (failed over 2): null
| Pool type: rpc
| Miner address: deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6x37y4w9xuszcqzfh5yy.Srv1
| Mining threads count: 12
| CPU affinity: [0->11]
| Batch mode: Yes
| Fee: 4.9%
| Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
| avx2: Yes
| avx512: No
| sha: No
-------------------------------------------
Using MH Engine
Connecting to wss://community-pools.mysrv.cloud:10300/ws/deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6x37y4w9xuszcqzfh5yy.Srv1
Unable to connect to any community nodes, exitting...

**Comment by WLASIX** [comment]
### A similar problem on Windows 10. Changing the pool did not help solve the problem:

_astrominer.exe -w dero1qyfmt60m2uhdau7yxqls44l6eqc4xzzmvhfruc83zjfzxdylkegfjqgyrgz4k -r dero.friendspool.club:10300 -p rpc_

> -------------------------------------------
> | MINER_VERSION: astrominer 1.8 BETA 2
> | COMPILED_TIME: Mar 12 2023
> | MINER_AUTHOR: astrominer
> | Pool: dero.friendspool.club:10300
> | Pool (failed over 1): null
> | Pool (failed over 2): null
> | Pool type: rpc
> | Miner address: dero1qyfmt60m2uhdau7yxqls44l6eqc4xzzmvhfruc83zjfzxdylkegfjqgyrgz4k
> | Mining threads count: 24
> | CPU affinity: [0->23]
> | Batch mode: Yes
> | Fee: 4.9%
> | AMD Ryzen 9 3900X 12-Core Processor
> | avx2: Yes
> | avx512: No
> | sha: Yes
> -------------------------------------------
> Using OS Engine
> Connecting to wss://dero.friendspool.club:10300/ws/dero1qyfmt60m2uhdau7yxqls44l6eqc4xzzmvhfruc83zjfzxdylkegfjqgyrgz4k←[0m
> Verified: OK
> [2023-03-13 01:27:21] [error] Server handshake response error: websocketpp.processor:20 (Invalid HTTP status.)
> [2023-03-13 01:27:21] [info] asio async_shutdown error: asio.ssl.stream:1 (stream truncated)
> ←[91mBroken pipeline... reconnecting in 3 seconds←[0m

**Comment by WLASIX** [comment]
Blockchain has a problem. The solution to the problem is to wait for the developers to fix it, they know about it. The issue can be closed

**Comment by dero-am** [comment]
@AlexanderGalchenko please check you connection to community pools

**Comment by AlexanderGalchenko** [comment]
telnet community-pools.mysrv.cloud 10300
Trying 130.61.26.47...
Connected to dero-node-overlode.mysrv.cloud.
Escape character is '^]'.
hello
Connection closed by foreign host.
root@server:~/dero2#

dpool port is open.

Other services work fine.

**Comment by dero-am** [comment]
@AlexanderGalchenko should be fine by now, the network was split last few days and nodes are not stable

**Comment by dero-am** [comment]
@AlexanderGalchenko please also make sure your address is registered. Community pools don't give back the specific error when your wallet is not registered.

**Comment by AlexanderGalchenko** [comment]
Wallet address works on HiveOS on this pool.
Problem is stay here.
-------------------------------------------
| MINER_VERSION: astrominer 1.8 BETA 4
| COMPILED_TIME: Mar 16 2023
| MINER_AUTHOR: astrominer
| Pool: community-pools.mysrv.cloud:10300
| Pool (failed over 1): null
| Pool (failed over 2): null
| Pool type: rpc
| Miner address: deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6x37y4w9xuszcqzfh5yy.Srv1
| Mining threads count: 12
| CPU affinity: [0->11]
| Batch mode: Yes
| Fee: 4.9%
| Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
| avx2: Yes
| avx512: No
| sha: No
-------------------------------------------
Using MH Engine
Connecting to wss://community-pools.mysrv.cloud:10300/ws/deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6x37y4w9xuszcqzfh5yy.Srv1
Unable to connect to any community nodes, exitting...

**Comment by dero-am** [comment]
the error is as what it showed _"Unable to connect to any community nodes, exitting..."_
Check below DNS if they work on your machine:
```
8.8.8.8
8.8.4.4
208.67.222.222
208.67.220.220
1.1.1.1
```
if the DNS aren't working, check your system config again if you have blocked/replaced it somewhere
if the DNS are fine, then you need to update your OS to use this miner because we use higher glibc version. There is no other way around.

**Comment by MrTalon63** [comment]
Once again miner seems to have problems with connecting to community nodes.

```
./astrominer -r dero.[REDACTED]:10100 -w [REDACTED]
-------------------------------------------
| MINER_VERSION: astrominer 1.8 BETA 4
| COMPILED_TIME: Mar 16 2023
| MINER_AUTHOR: astrominer
| Pool: dero.[REDACTED]:10100
| Pool (failed over 1): null
| Pool (failed over 2): null
| Pool type: rpc
| Miner address: [REDACTED]
| Mining threads count: 16
| CPU affinity: [0->15]
| Batch mode: Yes
| Fee: 4.9%
| Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
| avx2: Yes
| avx512: No
| sha: No
-------------------------------------------
Using MH Engine
Connecting to wss://dero.[REDACTED]:10100/ws/[REDACTED]
Unable to connect to any community nodes, exitting...
```
